export const columns = [
  // 샘플 데이터 칼럼
  {
    name: 'ID',
    selector: (row: {id: any}) => row.id,
  },
  {
    name: 'First Name',
    selector: (row: {firstName: any}) => row.firstName,
    sortable: true,
  },
  {
    name: 'Last Name',
    selector: (row: {lastName: any}) => row.lastName,
  },
  {
    name: 'Age',
    selector: (row: {age: any}) => row.age,
  },
  {
    name: 'Visits',
    selector: (row: {visits: any}) => row.visits,
  },
  {
    name: 'Status',
    selector: (row: {status: any}) => row.status,
  },
];

export const data = [
  // 샘플 데이터
  {
    id: 30,
    firstName: 'drawing-9olvj',
    lastName: 'replacement-x1hx4',
    age: 8,
    visits: 59,
    date: '2022-7-17',
    progress: 62,
    status: 'complicated',
  },
  {
    id: 14,
    firstName: 'perspective-y06jb',
    lastName: 'singer-yn7of',
    age: 29,
    visits: 39,
    date: '2022-3-2',
    progress: 11,
    status: 'single',
  },
  {
    id: 19,
    firstName: 'breath-rv8ma',
    lastName: 'degree-byy91',
    age: 4,
    visits: 22,
    date: '2022-3-30',
    progress: 28,
    status: 'relationship',
  },
  {
    id: 64,
    firstName: 'fang-x7col',
    lastName: 'day-ghxit',
    age: 15,
    visits: 36,
    date: '2022-1-2',
    progress: 85,
    status: 'complicated',
  },
  {
    id: 81,
    firstName: 'quarter-iatwb',
    lastName: 'discussion-lvd3x',
    age: 6,
    visits: 11,
    date: '2022-10-19',
    progress: 71,
    status: 'relationship',
  },
  {
    id: 94,
    firstName: 'mixture-b11gv',
    lastName: 'assistance-i1yde',
    age: 16,
    visits: 1,
    date: '2022-6-9',
    progress: 31,
    status: 'single',
  },
  {
    id: 24,
    firstName: 'brother-ckis8',
    lastName: 'start-li389',
    age: 26,
    visits: 82,
    date: '2022-7-3',
    progress: 3,
    status: 'single',
  },
  {
    id: 29,
    firstName: 'gold-c7z5p',
    lastName: 'article-grfkw',
    age: 14,
    visits: 6,
    date: '2022-10-21',
    progress: 74,
    status: 'relationship',
  },
  {
    id: 52,
    firstName: 'context-dy9si',
    lastName: 'mountain-ckiqc',
    age: 0,
    visits: 5,
    date: '2022-7-3',
    progress: 28,
    status: 'complicated',
  },
  {
    id: 86,
    firstName: 'rule-r3f8m',
    lastName: 'structure-aakl0',
    age: 15,
    visits: 26,
    date: '2022-11-17',
    progress: 83,
    status: 'complicated',
  },
  {
    id: 23,
    firstName: 'name-jtyp8',
    lastName: 'slip-f1wft',
    age: 17,
    visits: 53,
    date: '2022-3-25',
    progress: 42,
    status: 'relationship',
  },
  {
    id: 0,
    firstName: 'aunt-pkuqb',
    lastName: 'hall-091v6',
    age: 15,
    visits: 37,
    date: '2022-8-3',
    progress: 37,
    status: 'relationship',
  },
  {
    id: 81,
    firstName: 'fowl-htsdg',
    lastName: 'opportunity-8ylz7',
    age: 4,
    visits: 6,
    date: '2022-11-5',
    progress: 69,
    status: 'complicated',
  },
  {
    id: 6,
    firstName: 'advice-8xr34',
    lastName: 'act-5bwcu',
    age: 17,
    visits: 28,
    date: '2022-10-12',
    progress: 81,
    status: 'complicated',
  },
  {
    id: 28,
    firstName: 'circle-8ncz8',
    lastName: 'pizzas-5kc5k',
    age: 20,
    visits: 10,
    date: '2022-4-19',
    progress: 77,
    status: 'relationship',
  },
  {
    id: 79,
    firstName: 'army-bek3m',
    lastName: 'shop-4212c',
    age: 19,
    visits: 7,
    date: '2022-10-0',
    progress: 13,
    status: 'relationship',
  },
  {
    id: 81,
    firstName: 'organization-z13n0',
    lastName: 'weight-isj7d',
    age: 25,
    visits: 98,
    date: '2022-10-24',
    progress: 98,
    status: 'complicated',
  },
  {
    id: 74,
    firstName: 'wealth-do30c',
    lastName: 'selection-8s2lv',
    age: 22,
    visits: 24,
    date: '2022-7-30',
    progress: 2,
    status: 'single',
  },
  {
    id: 4,
    firstName: 'sympathy-ctb06',
    lastName: 'self-v25cr',
    age: 9,
    visits: 33,
    date: '2022-5-10',
    progress: 85,
    status: 'complicated',
  },
  {
    id: 47,
    firstName: 'muscle-7z0dc',
    lastName: 'jewel-l5jdp',
    age: 2,
    visits: 19,
    date: '2022-1-25',
    progress: 92,
    status: 'complicated',
  },
  {
    id: 89,
    firstName: 'pie-69b96',
    lastName: 'aspect-66mtn',
    age: 10,
    visits: 36,
    date: '2022-8-7',
    progress: 57,
    status: 'relationship',
  },
  {
    id: 8,
    firstName: 'government-8urxu',
    lastName: 'fuel-bbkla',
    age: 4,
    visits: 35,
    date: '2022-2-18',
    progress: 82,
    status: 'relationship',
  },
  {
    id: 80,
    firstName: 'daughter-m9mqg',
    lastName: 'feast-5lc3i',
    age: 22,
    visits: 66,
    date: '2022-2-24',
    progress: 6,
    status: 'complicated',
  },
  {
    id: 91,
    firstName: 'stone-7562f',
    lastName: 'digestion-tp96u',
    age: 29,
    visits: 16,
    date: '2022-5-16',
    progress: 72,
    status: 'complicated',
  },
  {
    id: 0,
    firstName: 'assumption-3rh1h',
    lastName: 'measure-zxynj',
    age: 6,
    visits: 31,
    date: '2022-10-3',
    progress: 52,
    status: 'complicated',
  },
  {
    id: 42,
    firstName: 'touch-6a9kn',
    lastName: 'storage-a5emt',
    age: 11,
    visits: 24,
    date: '2022-6-23',
    progress: 23,
    status: 'relationship',
  },
  {
    id: 51,
    firstName: 'bikes-a4f8j',
    lastName: 'snakes-s2w9o',
    age: 8,
    visits: 99,
    date: '2022-6-22',
    progress: 56,
    status: 'complicated',
  },
  {
    id: 20,
    firstName: 'twist-g1de9',
    lastName: 'plantation-37zdj',
    age: 24,
    visits: 47,
    date: '2022-8-15',
    progress: 28,
    status: 'complicated',
  },
  {
    id: 57,
    firstName: 'river-m213x',
    lastName: 'juice-77mk6',
    age: 1,
    visits: 14,
    date: '2022-5-22',
    progress: 35,
    status: 'relationship',
  },
  {
    id: 73,
    firstName: 'arm-3a216',
    lastName: 'moment-f6b6r',
    age: 26,
    visits: 38,
    date: '2022-3-6',
    progress: 79,
    status: 'complicated',
  },
  {
    id: 17,
    firstName: 'crowd-6joil',
    lastName: 'form-qajmb',
    age: 12,
    visits: 31,
    date: '2022-4-18',
    progress: 73,
    status: 'complicated',
  },
  {
    id: 95,
    firstName: 'yarn-xu5dk',
    lastName: 'vegetable-boc9p',
    age: 23,
    visits: 53,
    date: '2022-11-23',
    progress: 69,
    status: 'single',
  },
  {
    id: 12,
    firstName: 'spoon-imqw9',
    lastName: 'branch-lhnek',
    age: 13,
    visits: 66,
    date: '2022-1-27',
    progress: 49,
    status: 'relationship',
  },
  {
    id: 49,
    firstName: 'baby-l1x81',
    lastName: 'health-az8lh',
    age: 23,
    visits: 93,
    date: '2022-7-4',
    progress: 30,
    status: 'single',
  },
  {
    id: 42,
    firstName: 'tendency-r4r3v',
    lastName: 'sink-507j5',
    age: 12,
    visits: 33,
    date: '2022-11-6',
    progress: 84,
    status: 'relationship',
  },
  {
    id: 46,
    firstName: 'pull-fi7ar',
    lastName: 'name-p6pia',
    age: 22,
    visits: 18,
    date: '2022-11-25',
    progress: 76,
    status: 'relationship',
  },
  {
    id: 13,
    firstName: 'cook-k2a3b',
    lastName: 'hand-9g3gw',
    age: 16,
    visits: 6,
    date: '2022-3-8',
    progress: 0,
    status: 'single',
  },
];
